import productImage from 'public/images/p.jpg';
import hoodie from 'public/images/hoodie.png';

import { IProductItemCard, IHistoryResponse, TokensType } from './types';

const userTokens: TokensType[] = [
  {
    symbol: 'dai',
    logo: '',
  },
  {
    symbol: 'usdt',
    logo: '',
  },
  {
    symbol: 'xlm',
    logo: '',
  },
];
const singleToken: TokensType = {
  symbol: 'usdc',
  logo: require(`/public/images/tokens/usdc.svg`),
};

export const products: IProductItemCard[] = [
  {
    title: 'Purple Hoodie',
    method: ['single', 'stream'],
    id: '1',
    tokens: userTokens,
    amount: '$100000005',
    image: productImage,
  },
  {
    title: 'Purple Hoodie',
    method: 'vesting',
    id: '345837',
    tokens: userTokens,
    amount: '$1500',
    image: hoodie,
  },
  {
    title: 'Purple Hoodie',
    method: ['vesting', 'stream'],
    id: '345',
    tokens: userTokens,
    amount: '$2544445',
    image: productImage,
  },
  {
    title: 'Purple Hoodie',
    method: 'single',
    id: '54654333355',
    tokens: userTokens,
    amount: '$34510',
    image: hoodie,
  },
  {
    title: 'Purple Hoodie',
    method: 'vesting',
    id: '54654',
    tokens: userTokens,
    amount: '$15',
    image: productImage,
  },
  {
    title: 'Purple Hoodie',
    method: 'single',
    id: '54654',
    tokens: userTokens,
    amount: '$15',
    image: hoodie,
  },
  {
    title: 'Purple Hoodie',
    method: 'single',
    id: '54654',
    tokens: userTokens,
    amount: '$15',
    image: productImage,
  },
  {
    title: 'Purple Hoodie',
    method: 'vesting',
    id: '546545555',
    tokens: userTokens,
    amount: '$15',
    image: hoodie,
  },
  {
    title: 'Purple Hoodie',
    method: 'stream',
    id: '54654',
    tokens: userTokens,
    amount: '$1544444',
    image: productImage,
  },
];

export const history: IHistoryResponse[] = [
  {
    title: 'XXXXXXXXXXXX Hoodie',
    method: 'single',
    id: '1',
    token: singleToken,
    amount: '$15',
    image: productImage,
    date: Date.now(),
    cancellableAfter: Date.now() - 200,
    status: 'active',
    sender: '0x600',
    progress: 90,
  },
  {
    title: 'XXXXXX Hoodie',
    method: 'vesting',
    id: '345837',
    token: singleToken,
    amount: '$1500',
    image: hoodie,
    date: Date.now(),
    status: 'completed',
    sender: '0x600',
    progress: 30,
  },
  {
    title: 'X Hoodie',
    method: 'stream',
    id: '3422',
    token: singleToken,
    amount: '$1500000',
    image: hoodie,
    date: Date.now(),
    status: 'cancelled',
    sender: '0x600',
    progress: 20,
  },
  {
    title: 'XXXXXXXXXXXX Hoodie',
    method: 'single',
    id: '12',
    token: singleToken,
    amount: '$15',
    image: productImage,
    date: Date.now(),
    status: 'active',
    sender: '0x600',
  },
  {
    title: 'XXXXXX Hoodie',
    method: 'vesting',
    id: '222',
    token: singleToken,
    amount: '$1500',
    image: hoodie,
    date: Date.now(),
    status: 'completed',
    sender: '0x600',
  },
  {
    title: 'X Hoodie',
    method: 'stream',
    id: '3334',
    token: singleToken,
    amount: '$1500000',
    image: hoodie,
    date: Date.now(),
    status: 'cancelled',
    sender: '0x600',
  },
  {
    title: 'X Hoodie',
    method: 'stream',
    id: '33334',
    token: singleToken,
    amount: '$1500000',
    image: hoodie,
    date: Date.now(),
    status: 'cancelled',
    sender: '0x600',
  },
  {
    title: 'X Hoodie',
    method: 'stream',
    id: '322334',
    token: singleToken,
    amount: '$1500000',
    image: hoodie,
    date: Date.now(),
    status: 'cancelled',
    sender: '0x600',
  },
  {
    title: 'X Hoodie',
    method: 'stream',
    id: '2312',
    token: singleToken,
    amount: '$1500000',
    image: hoodie,
    date: Date.now(),
    status: 'cancelled',
    sender: '0x600',
  },
];
